name: "Python FoD SAST Scan"
description: "Runs a Fortify on Demand Scan of a Python application"
inputs:
  working_directory:
    required: false
    description: "Relative directory (from root of repository) from where to run commands"
    default: "."
  fod_url:
    required: false
    description: "FoD API URI"
    default: "https://ams.fortify.com"
  fod_api_url:
    required: false
    description: "FoD API URI"
    default: "https://api.ams.fortify.com"
  fod_client_id:
    required: true
    description: "FoD API Client Id"
  fod_client_secret:
    required: true
    description: "FoD API Client Secret"
  fod_app_name:
    required: true
    description: "FoD Application Name"
  fod_release_name:
    required: true
    description: "FoD Release Name"
  fod_parent_release_name:
    required: false
    description: "FoD Parent Release Name"
    default: "develop"
  python_version:
    required: false
    description: "Version of Python to use"
    default: "3.12.3"
outputs:
  fod_scan_id:
    description: "FoD Scan Id"
    value: ${{ steps.fod-sast-scan.outputs.fod_scan_id }}
runs:
  using: "composite"
  steps:
    # Java is required to run the various Fortify utilities.
    # Setup JDK 11 on host
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    # Install appropriate version of Python and activate venv
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Activate virtualenv
      shell: bash
      run: |
        python -m venv .venv
        . .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
    - name: Install dependencies
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: pip install -r requirements.txt        
    # Install Fortify tools
    - name: Setup Fortify tools
      uses: fortify/github-action/setup@v1
      with:
        export-path: true
        fcli: latest
        sc-client: latest
        fod-uploader: skip
        vuln-exporter: latest
        bugtracker-utility: skip
    # Login to Fortify on Demand fcli session
    - name: Login fcli
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        fcli --version
        fcli fod session login --url $FOD_API_URI --client-id $FOD_CLIENT_ID --client-secret $FOD_CLIENT_SECRET --session github-actions
      env:
        FOD_API_URI: ${{ inputs.fod_api_url }}
        FOD_CLIENT_ID: ${{ inputs.fod_client_id }}
        FOD_CLIENT_SECRET: ${{ inputs.fod_client_secret }}
    # Create a new Fortify on Demand release for GitHub branch
    - name: Create FoD release
      id: create-release
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        fcli fod release list --app "$FOD_APP_NAME" --session github-actions
        echo fcli fod release create "${FOD_APP_NAME}:${FOD_RELEASE_NAME}" --description "Created automatically from GitHub" --copy-from "${FOD_APP_NAME}:${FOD_PARENT_RELEASE_NAME}" --status Development --skip-if-exists -o expr="{releaseId}" --session github-actions
        RELID=$(fcli fod release create "${FOD_APP_NAME}:${FOD_RELEASE_NAME}" --description "Created automatically from GitHub" --copy-from "${FOD_APP_NAME}:${FOD_PARENT_RELEASE_NAME}" --status Development --skip-if-exists -o expr="{releaseId}" --session github-actions)
        echo "::debug::Created/Using fod_release_id=${RELID}"
        echo "release_id=${RELID}" >> $GITHUB_OUTPUT
      env:
        FOD_APP_NAME: ${{ inputs.fod_app_name }}
        FOD_RELEASE_NAME: ${{ inputs.fod_release_name }}
        FOD_PARENT_RELEASE_NAME: ${{ inputs.fod_parent_release_name }}
    # Create FoD upload package using ScanCentral "package" action
    - name: Package Code
      uses: fortify/github-action/package@v1
      env:
        EXTRA_PACKAGE_OPTS: -bt none --python-virtual-env .venv
        PACKAGE_FILE: "package"
    # Start Fortify on Demand SAST scan and wait until results complete.
    - name: Perform FoD SAST scan
      id: fod-sast-scan
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        fcli fod sast-scan start --release "${FOD_RELEASE_NAME}" --notes "${FOD_SCAN_NOTES}" -f $PACKAGE_FILE --store curScan --session github-actions
        sleep 10
        echo "fod_scan_id=$(fcli util var contents curScan -o 'expr={scanId}')" >> $GITHUB_OUTPUT
        fcli fod sast-scan wait-for ::curScan:: --session github-actions
      env:
        PACKAGE_FILE: "package.zip"
        FOD_RELEASE_NAME: ${{ format('{0}:{1}', inputs.fod_app_name, inputs.fod_release_name) }}
        FOD_SCAN_NOTES: "Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
    # Export FoD vulnerability data to GitHub
    - name: Export FoD vulnerability data to GitHub
      #uses: fortify/github-action/fod-export@v1
      uses: kadraman/github-action/fod-export@fve-space-issues
      env:
        FOD_URL: ${{ inputs.fod_url }}
        FOD_CLIENT_ID: ${{ inputs.fod_client_id }}
        FOD_CLIENT_SECRET: ${{ inputs.fod_client_secret }}
        FOD_RELEASE: ${{ format('{0}:{1}', inputs.fod_app_name, inputs.fod_release_name) }}
        #FOD_RELEASE: ${{ steps.create-release.outputs.release_id }}
    # Logout/Close Fortify on Demand fcli session
    - name: Logout fcli
      shell: bash
      run: |
        fcli fod session logout --session github-actions
